"""Generate FL_API_COVERAGE.md by diffing fl-openapi.json against
backend code. Greps main.py / flashlive_feed.py / enrichment/*.py
for /v1/* paths to find which FL endpoints we actually call.

Run: python3 fl_probe/coverage.py > FL_API_COVERAGE.md

Stdlib-only — same constraint as the other probe scripts so it can
run in CI without extra deps.
"""
import datetime
import json
import os
import re
import subprocess
import sys


def main() -> None:
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    spec_path = os.path.join(repo_root, "fl-openapi.json")
    if not os.path.exists(spec_path):
        sys.exit(f"missing {spec_path} — re-download from HugeAPI portal")

    with open(spec_path) as f:
        spec = json.load(f)

    fl: dict = {}
    for path, ops in spec["paths"].items():
        op = ops.get("get", {})
        tags = op.get("tags", [])
        fl[path] = {
            "tag": tags[0] if tags else "?",
            "summary": op.get("summary", ""),
            "params": [p["name"] for p in op.get("parameters", [])
                       if p["name"] != "locale"],
        }

    # Grep backend for /v1/* path literals. The regex allows digits
    # (so /v1/events/h2h matches), lowercase, hyphens, slashes.
    cmd_paths = (
        "grep -hoE '/v1/[a-z0-9/-]+' "
        "main.py flashlive_feed.py enrichment/*.py 2>/dev/null | "
        "sort -u"
    )
    raw = subprocess.run(cmd_paths, cwd=repo_root, shell=True,
                         capture_output=True, text=True).stdout
    backend = set(line for line in raw.strip().split("\n") if line)

    cmd_routes = (
        r"""grep -hoE '@app\.get\("/api/event/\{ticker\}/[a-z-]+' main.py | """
        r"""sed 's|@app.get("||'"""
    )
    raw = subprocess.run(cmd_routes, cwd=repo_root, shell=True,
                         capture_output=True, text=True).stdout
    api_routes = set(line for line in raw.strip().split("\n") if line)

    by_tag: dict = {}
    for path, meta in sorted(fl.items()):
        is_covered = path in backend
        by_tag.setdefault(meta["tag"], []).append((path, meta, is_covered))

    total = len(fl)
    total_covered = sum(1 for items in by_tag.values()
                        for _, _, c in items if c)

    print("# FlashLive API Coverage")
    print()
    print("> Generated by `python3 fl_probe/coverage.py` against")
    print("> `fl-openapi.json` and our backend (`main.py`,")
    print("> `flashlive_feed.py`, `enrichment/*.py`). Re-run when")
    print("> adding new wrappers or after FL ships new endpoints.")
    print(">")
    print(f"> **Headline:** {total_covered}/{total} FL endpoints reached by")
    print(f"> backend ({len(api_routes)} `/api/event/{{ticker}}/*` wrappers).")
    print(f"> Last regenerated: {datetime.date.today()}.")
    print()
    print("## Strategic summary")
    print()
    print("Coverage falls into three buckets, each with a different")
    print("intended end state. Numbers below recompute on every run —")
    print("they reflect the live state of the codebase + spec.")
    print()
    # Three buckets — group tags by intent. Numbers below recompute
    # automatically as wrappers are added.
    EVENT_LEVEL = {"events"}                          # modal + list-main-odds
    DRILL_IN = {"players", "teams", "tournaments", "news"}
    UTILITY = {"sports", "search", "rankings", "images"}

    def bucket_stats(tags: set) -> tuple:
        items = [it for tag in tags for it in by_tag.get(tag, [])]
        n = len(items)
        c = sum(1 for _, _, is_cov in items if is_cov)
        pct = round(100 * c / n) if n else 0
        return c, n, pct

    ev_c, ev_n, ev_p = bucket_stats(EVENT_LEVEL)
    di_c, di_n, di_p = bucket_stats(DRILL_IN)
    ut_c, ut_n, ut_p = bucket_stats(UTILITY)

    def bucket_emoji(pct: int) -> str:
        if pct >= 80:
            return "⭐"
        if pct >= 50:
            return "🟡"
        return "🚧"

    print("| Bucket | Coverage | Status |")
    print("|---|---|---|")
    print(f"| **Event-level (modal + bulk slate)** | "
          f"{ev_c}/{ev_n} = {ev_p}% | "
          f"{bucket_emoji(ev_p)} Modal endpoint family. Gaps here are "
          f"deliberate (Round-1 #3 Odds, parked Q1 cricket-alt, "
          f"racing-details = no FL data per probe v4). |")
    print(f"| **Drill-in (browse + profile pages)** | "
          f"{di_c}/{di_n} = {di_p}% | "
          f"{bucket_emoji(di_p)} L1/L2 nav pages (sport, tournament) + "
          f"post-MVP team/player profile + news module. |")
    print(f"| **Utility** | "
          f"{ut_c}/{ut_n} = {ut_p}% | "
          f"{bucket_emoji(ut_p)} Cross-cutting endpoints — search, "
          f"rankings, sport meta. `/v1/images/data` typically "
          f"unnecessary (URLs already inline elsewhere). |")
    print()
    print("## Per-endpoint detail")
    print()
    for tag in sorted(by_tag):
        items = by_tag[tag]
        n_covered = sum(1 for _, _, c in items if c)
        print(f"### `{tag}` — {n_covered}/{len(items)} covered")
        print()
        print("| Status | Path | Required params (excl. locale) | Summary |")
        print("|---|---|---|---|")
        for path, meta, is_covered in items:
            mark = "✅" if is_covered else "⚪"
            params = ", ".join(meta["params"]) if meta["params"] else "(none)"
            summary = meta["summary"].replace("|", "\\|")
            print(f"| {mark} | `{path}` | {params} | {summary} |")
        print()

    print("## Gap analysis")
    print()
    print("### Event-level gaps (modal-relevant)")
    print()
    print("| Endpoint | Why not covered | Recommended action |")
    print("|---|---|---|")
    print("| `/v1/events/commentary-alt` | Cricket-specific. Tied to Q1 "
          "(scorecard family 404s on canonical) | Park until Q1 resolves |")
    print("| `/v1/events/list-main-odds` | Round-1 #3 Odds deferred | "
          "Pick up when ready to do Odds |")
    print("| `/v1/events/prematch-odds` | Round-1 #3 Odds deferred | "
          "Pick up when ready to do Odds |")
    print("| `/v1/events/racing-details` | Probe v4: 404 on canonical → "
          "no FL data via current API (Tier G) | Skip — wasted work |")
    print()
    print("### Drill-in / Step E gaps")
    print()
    print("| Family | Endpoints | Step-E target |")
    print("|---|---|---|")
    print("| `/v1/players/*` | data, career, transfers, last-events, "
          "alt-events | Player profile page |")
    print("| `/v1/tournaments/*` | fixtures, results, stages, "
          "seasons/data, popular, stages/seasons | League / season page |")
    print("| `/v1/news/*` | categories, list, top, summary, details, "
          "related, most-read | Richer news module (existing news tab "
          "uses other infra) |")
    print("| `/v1/teams/news`, `/v1/teams/transfers` | 2 endpoints | "
          "Team profile page (combines with `/teams/data` etc. already "
          "wrapped) |")
    print("| `/v1/rankings/list`, `/v1/rankings/data` | 2 endpoints | "
          "Rankings sub-section on league page (Tennis ATP/WTA, Golf) |")
    print()
    print("### Utility gaps")
    print()
    print("| Endpoint | Use case | Effort |")
    print("|---|---|---|")
    print("| `/v1/sports/events-count` | Top-nav 'X live games' badges "
          "per sport | ~10 min |")
    print("| `/v1/images/data` | Fetch a specific image_id — likely "
          "never needed (URLs already inline elsewhere) | Skip |")


if __name__ == "__main__":
    main()
