"""Germany â€” BBL seed manifest DRAFT.

Autogenerated by scripts/fl_universe_batch.py.
FL stage_id: rXnrx7Ca
FL stage_name: Main
FL season_id: O6TXI3cK

PILOT SKELETON ONLY â€” operator review required before apply.
INSERT canonicals are BLANK (Amendment #24: FL provides
structure not identity; operator fills canonical_name).
BACKFILL canonicals preserve the existing sp.teams canonical.
FL canonical is in the aliases tuple as a starting point;
layer in additional alias variants per Pattern A.2 production
discovery before apply.
"""
from __future__ import annotations


LEAGUE_ALIAS_SOURCE = "bootstrap_league_coverage"


# Format: (canonical_name, country_code, aliases_tuple, notes)
LEAGUE_TEAMS_SEED: list[tuple[str, str, tuple[str, ...], str]] = [
    ("Bayern", "DEU",
     ("Bayern",),
     "BACKFILL from FL team_id=6LstMRPo; sp.teams.id=b4318e7f-9ee5-4c0d-9c5d-33280c1920ab"),

    ("Alba Berlin", "DEU",
     ("Alba Berlin",),
     "PILOT BACKFILL from FL team_id=ncLyc03K; sp.teams.id=7b206ac6-3ff5-4141-b235-474f6db7686a"),

    ("Telekom Baskets Bonn", "DEU",
     ("Bonn",),
     "INSERT from FL team_id=86MXctlE; canonical operator-filled per Amendment #24"),

    ("Wurzburg", "DEU",
     ("Wurzburg",),
     "PILOT BACKFILL from FL team_id=0bukcrmo; sp.teams.id=358d0544-9ab7-4216-871a-e972d17a7e9b"),

    ("Ratiopharm Ulm", "DEU",
     ("Ulm",),
     "INSERT from FL team_id=fcks1zeJ; canonical operator-filled per Amendment #24"),

    ("Vechta", "DEU",
     ("Vechta",),
     "PILOT BACKFILL from FL team_id=vy2cTqpo; sp.teams.id=87d4c8c9-b17f-4428-b4d3-29666f4326e7"),

    ("Trier", "DEU",
     ("Trier",),
     "PILOT BACKFILL from FL team_id=QL5yPwmQ; sp.teams.id=d7c99331-9d6a-49f6-b796-b6b242c40fa5"),

    ("Rostock", "DEU",
     ("Rostock",),
     "PILOT BACKFILL from FL team_id=SnRANHqC; sp.teams.id=1b81310d-6e53-4a90-8604-7e49718d311c"),

    ("Ludwigsburg", "DEU",
     ("Ludwigsburg",),
     "PILOT BACKFILL from FL team_id=rZFPnFXL; sp.teams.id=b393f523-9ada-4c88-b42d-226178ab2f6e"),

    ("Oldenburg", "DEU",
     ("Oldenburg",),
     "PILOT BACKFILL from FL team_id=fRK1cKIQ; sp.teams.id=6fa290e6-8870-4332-b25d-1d0b4b9418f5"),

    ("Chemnitz", "DEU",
     ("Chemnitz",),
     "PILOT BACKFILL from FL team_id=hInQh5sp; sp.teams.id=d7f3ffd3-c621-4dd5-b91f-a903445860e7"),

    ("Syntainics MBC", "DEU",
     ("Syntainics MBC",),
     "PILOT BACKFILL from FL team_id=Ue0Tyv7T; sp.teams.id=b27a26b8-9873-4d89-b7a0-a2c10d7dd951"),

    ("Hamburg", "DEU",
     ("Hamburg",),
     "PILOT BACKFILL from FL team_id=zyBCtTHn; sp.teams.id=09624eed-4b9b-47f1-ab7f-87bc1a7416b5"),

    ("Frankfurt", "DEU",
     ("Frankfurt",),
     "PILOT BACKFILL from FL team_id=zy99LdBD; sp.teams.id=0192be15-63cb-434e-a183-5214f0d10e38"),

    ("Jena", "DEU",
     ("Jena",),
     "PILOT BACKFILL from FL team_id=CI1XPJXJ; sp.teams.id=9777b05c-ad64-4c86-b8d0-f09947d080f9"),

    ("Basketball Braunschweig", "DEU",
     ("Basketball Braunschweig",),
     "PILOT BACKFILL from FL team_id=Kz1C1dQ6; sp.teams.id=588ea905-2904-45c1-9e1e-78fcff590281"),

    ("Heidelberg", "DEU",
     ("Heidelberg",),
     "PILOT BACKFILL from FL team_id=EXzZjqCd; sp.teams.id=36cf720f-beae-48ae-9941-4a4d4e959aec"),

]
