"""Bootstrap sp.teams + sp.team_aliases from legacy public.entities + public.entity_aliases.

Phase 2A.5 deliverable per SP Architecture v1.4 §5 / Phase 2B design
doc Question B. One-time migration (idempotent — re-running is a
no-op for any rows already present).

What it does:

  Step 1  Resolves legacy entity sport names → sp.sports.id via the
          name column (which the seed_sp_sports migration matches to
          legacy values like 'Soccer', 'Basketball', etc.).

  Step 2  Migrates `public.entities` rows where entity_type='team'
          and sport IS NOT NULL into sp.teams. Re-normalizes the
          canonical_name via resolver._normalize.normalize_name (the
          legacy `normalized` column was generated by a different
          routine; we redo it for consistency with the resolver's
          matching path).

          Builds an in-memory map: legacy_entity_id → sp_team_id.

  Step 3  Migrates `public.entity_aliases` rows whose entity_id
          appears in the team-typed map into sp.team_aliases:
            alias            = original encoding (preserved)
            alias_normalized = re-normalized via resolver._normalize
            source           = 'legacy_bootstrap'
            confidence       = 0.95

          Idempotent via the (alias_normalized, source) unique
          constraint — re-running skips already-bootstrapped rows.

What it does NOT do:

  * Migrate non-team entities (players, leagues, assets) — those
    aren't part of the resolver's matching surface in 2B.
  * Migrate public.markets — deferred to 2C per design doc.
  * Touch sp.fixtures or any provider record table.
  * Modify legacy public.* tables in any way (read-only).

Output:
  Per-sport / per-source counts to stdout (and via structlog so
  Railway logs can record the run). Logs the count of skipped rows
  with reasons.

Usage:

    DATABASE_URL=<prod-Neon-URL> python scripts/bootstrap_sp_teams.py

    # or via Makefile against docker-compose dev DB:
    make bootstrap-sp-teams
"""
from __future__ import annotations

import argparse
import asyncio
import os
import sys
import uuid
from collections import defaultdict
from typing import Any

# Make project root importable when invoked as `python scripts/...`.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


async def main(dry_run: bool) -> int:
    from sqlalchemy import text
    from sqlalchemy.dialects.postgresql import insert as pg_insert

    from db import async_session, DATABASE_URL
    if not DATABASE_URL or async_session is None:
        print("ERROR: DATABASE_URL not set; bootstrap requires Postgres.", file=sys.stderr)
        return 2

    from observability import get_logger
    from resolver._normalize import normalize_name
    from sp_models import Sport, Team, TeamAlias

    log = get_logger("bootstrap.sp_teams")

    log.info("bootstrap.sp_teams.start", dry_run=dry_run)

    async with async_session() as session:
        # Step 1: load sp.sports name → id map.
        sports_rows = (await session.execute(
            text("SELECT id, name FROM sp.sports")
        )).all()
        sport_id_by_name = {row.name: row.id for row in sports_rows}
        if not sport_id_by_name:
            print(
                "ERROR: sp.sports is empty. Run `alembic upgrade head` "
                "to apply the seed_sp_sports migration first.",
                file=sys.stderr,
            )
            return 3

        log.info("bootstrap.sp_teams.sports_loaded", count=len(sport_id_by_name))

        # Step 2: read legacy team entities.
        team_entities = (await session.execute(text(
            """
            SELECT id, canonical_name, sport, league
            FROM public.entities
            WHERE entity_type = 'team' AND sport IS NOT NULL
            """
        ))).all()
        log.info("bootstrap.sp_teams.legacy_entities_loaded",
                 count=len(team_entities))

        # Insert teams; build legacy → sp map.
        legacy_to_sp: dict[int, uuid.UUID] = {}
        per_sport_inserts: dict[str, int] = defaultdict(int)
        per_sport_skipped: dict[str, int] = defaultdict(int)
        unmapped_sports: dict[str, int] = defaultdict(int)

        for ent in team_entities:
            sport_id = sport_id_by_name.get(ent.sport)
            if sport_id is None:
                unmapped_sports[ent.sport] += 1
                continue

            normalized = normalize_name(ent.canonical_name)
            if not normalized:
                per_sport_skipped[ent.sport] += 1
                continue

            # INSERT ... ON CONFLICT DO NOTHING on (sport_id,
            # normalized_name) is what we'd want, but sp.teams
            # doesn't have a unique constraint on that pair (only
            # an index). Use a SELECT-then-INSERT pattern with a
            # canonical_name + sport_id check to avoid duplicates.
            # Safe because this script runs single-threaded.
            existing = (await session.execute(text(
                """
                SELECT id FROM sp.teams
                WHERE sport_id = :sport_id AND normalized_name = :normalized
                LIMIT 1
                """
            ).bindparams(sport_id=sport_id, normalized=normalized))).scalar_one_or_none()

            if existing is not None:
                legacy_to_sp[ent.id] = existing
                continue

            new_id = uuid.uuid4()
            if not dry_run:
                await session.execute(text(
                    """
                    INSERT INTO sp.teams (id, sport_id, canonical_name, normalized_name)
                    VALUES (:id, :sport_id, :canonical_name, :normalized)
                    """
                ).bindparams(
                    id=new_id,
                    sport_id=sport_id,
                    canonical_name=ent.canonical_name,
                    normalized=normalized,
                ))
            legacy_to_sp[ent.id] = new_id
            per_sport_inserts[ent.sport] += 1

        if not dry_run:
            await session.commit()

        log.info(
            "bootstrap.sp_teams.teams_migrated",
            inserted_per_sport=dict(per_sport_inserts),
            skipped_per_sport=dict(per_sport_skipped),
            unmapped_sports=dict(unmapped_sports),
            total_inserted=sum(per_sport_inserts.values()),
            total_mapped=len(legacy_to_sp),
        )

        # Step 3: migrate aliases.
        aliases = (await session.execute(text(
            """
            SELECT a.id, a.entity_id, a.alias, a.source
            FROM public.entity_aliases a
            INNER JOIN public.entities e ON e.id = a.entity_id
            WHERE e.entity_type = 'team' AND e.sport IS NOT NULL
            """
        ))).all()

        log.info("bootstrap.sp_teams.legacy_aliases_loaded", count=len(aliases))

        alias_inserted = 0
        alias_skipped_no_team = 0
        alias_skipped_empty_norm = 0

        for a in aliases:
            sp_team_id = legacy_to_sp.get(a.entity_id)
            if sp_team_id is None:
                alias_skipped_no_team += 1
                continue

            alias_normalized = normalize_name(a.alias)
            if not alias_normalized:
                alias_skipped_empty_norm += 1
                continue

            if not dry_run:
                await session.execute(text(
                    """
                    INSERT INTO sp.team_aliases
                      (id, team_id, alias, alias_normalized, source, confidence)
                    VALUES
                      (gen_random_uuid(), :team_id, :alias, :alias_normalized, :source, :confidence)
                    ON CONFLICT (alias_normalized, source) DO NOTHING
                    """
                ).bindparams(
                    team_id=sp_team_id,
                    alias=a.alias,
                    alias_normalized=alias_normalized,
                    source="legacy_bootstrap",
                    confidence=0.95,
                ))
            alias_inserted += 1

        if not dry_run:
            await session.commit()

        log.info(
            "bootstrap.sp_teams.aliases_migrated",
            attempted=alias_inserted,
            skipped_no_team_in_map=alias_skipped_no_team,
            skipped_empty_normalized=alias_skipped_empty_norm,
        )

        # Final sanity counts.
        if not dry_run:
            sp_teams_count = (await session.execute(text(
                "SELECT COUNT(*) FROM sp.teams"
            ))).scalar_one()
            sp_aliases_count = (await session.execute(text(
                "SELECT COUNT(*) FROM sp.team_aliases WHERE source = 'legacy_bootstrap'"
            ))).scalar_one()
            log.info(
                "bootstrap.sp_teams.final_counts",
                sp_teams_total=sp_teams_count,
                sp_team_aliases_legacy_bootstrap=sp_aliases_count,
            )
            print(f"\nBootstrap complete:")
            print(f"  sp.teams total:                        {sp_teams_count:>8}")
            print(f"  sp.team_aliases (legacy_bootstrap):    {sp_aliases_count:>8}")
            if unmapped_sports:
                print(f"\n  Skipped — unmapped sports in legacy data:")
                for sport, count in sorted(unmapped_sports.items()):
                    print(f"    {sport!r:30}  {count:>6} entities")

    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Read everything but don't write. Logs counts of what "
             "would be inserted. Use to verify mapping coverage "
             "before committing.",
    )
    args = parser.parse_args()
    rc = asyncio.run(main(dry_run=args.dry_run))
    sys.exit(rc)
